### ISSUE TITLE
Add an anchor for each contributor

### ISSUE THREAD

**Issue by Bounga** [hanami/contributors#40]
It would be great to add an anchor on each entry (tr) based on user handle so every contributor could show its pride of being an Hanami contributor and link to its row on hanami-contributors. What do you think of it? It would be easy to add and I can write a PR for it if needed.

**Comment by cllns** [comment]
Thanks for the suggestion!

People can link to their page: http://contributors.hanamirb.org/contributors/cllns, which is better, I think?

But there's no count on that page. Maybe that's the solution for this problem instead? What do you think?

**Comment by Bounga** [comment]
Oh! I didn't know about this, that's a perfect fit. But yes it would be great to add the commits count. We should do something to help contributors to discover this URL. Could we find a way to link it on the main page?

Also if I try to access `https://github.com/hanami/contributors/bounga` I do have a 500. My handle starts with a capital letter but if we can do something about that it would be cool.

**Comment by cllns** [comment]
It is linked from the main page, if you click the user's handle :)

http://contributors.hanamirb.org/contributors/Bounga works for me (and is linked uppercase too from the main page)

**Comment by Bounga** [comment]
Oh sorry. Missed that… I'm going to flog myself. Don't know how I didn't saw this. Closing this issue. thanks a lot @cllns

**Comment by Bounga** [comment]
I'll do this. Thanks for the suggestion and help.

**Comment by Bounga** [comment]
BTW Luca is far ahead of me. How am I going to catch him… 🤣

**Comment by Bounga** [comment]
I'd like to go on with "add page with all projects in db" task. Do you think I can fork my  own branch to do this ?
