### ISSUE TITLE
Demo app is failing

### ISSUE THREAD

**Issue by seanfcarroll** [hanami/contributors#49]
<img width="613" alt="screen shot 2018-02-18 at 17 55 52" src="https://user-images.githubusercontent.com/11340230/36354451-053a5d58-14d5-11e8-9c67-25e2f92c5858.png">

**Comment by davydovanton** [comment]
Hm, thanks for report. I’ll fix it

**Comment by davydovanton** [comment]
done. Now all works correct 💯
